insert into City values (1,'Kabul','AFG','Kabol',1780000);
insert into City values (2,'Qandahar','AFG','Qandahar',237500);
insert into City values (3,'Herat','AFG','Herat',186800);
insert into City values (4,'Mazar-e-Sharif','AFG','Balkh',127800);
insert into City values (5,'Amsterdam','NLD','Noord-Holland',731200);
insert into City values (6,'Rotterdam','NLD','Zuid-Holland',593321);
insert into City values (7,'Haag','NLD','Zuid-Holland',440900);
insert into City values (8,'Utrecht','NLD','Utrecht',234323);
insert into City values (9,'Eindhoven','NLD','Noord-Brabant',201843);
insert into City values (10,'Tilburg','NLD','Noord-Brabant',193238);
insert into City values (11,'Groningen','NLD','Groningen',172701);
insert into City values (12,'Breda','NLD','Noord-Brabant',160398);
insert into City values (13,'Apeldoorn','NLD','Gelderland',153491);
insert into City values (14,'Nijmegen','NLD','Gelderland',152463);
insert into City values (15,'Enschede','NLD','Overijssel',149544);
insert into City values (16,'Haarlem','NLD','Noord-Holland',148772);
insert into City values (17,'Almere','NLD','Flevoland',142465);
insert into City values (18,'Arnhem','NLD','Gelderland',138020);
insert into City values (19,'Zaanstad','NLD','Noord-Holland',135621);
insert into City values (20,'s-Hertogenbosch','NLD','Noord-Brabant',129170);
insert into City values (21,'Amersfoort','NLD','Utrecht',126270);
insert into City values (22,'Maastricht','NLD','Limburg',122087);
insert into City values (23,'Dordrecht','NLD','Zuid-Holland',119811);
insert into City values (24,'Leiden','NLD','Zuid-Holland',117196);
insert into City values (25,'Haarlemmermeer','NLD','Noord-Holland',110722);
insert into City values (26,'Zoetermeer','NLD','Zuid-Holland',110214);
insert into City values (27,'Emmen','NLD','Drenthe',105853);
insert into City values (28,'Zwolle','NLD','Overijssel',105819);
insert into City values (29,'Ede','NLD','Gelderland',101574);
insert into City values (30,'Delft','NLD','Zuid-Holland',95268);
insert into City values (31,'Heerlen','NLD','Limburg',95052);
insert into City values (32,'Alkmaar','NLD','Noord-Holland',92713);
insert into City values (33,'Willemstad','ANT','Curaao',2345);
insert into City values (34,'Tirana','ALB','Tirana',270000);
insert into City values (35,'Alger','DZA','Alger',2168000);
insert into City values (36,'Oran','DZA','Oran',609823);
insert into City values (37,'Constantine','DZA','Constantine',443727);
insert into City values (38,'Annaba','DZA','Annaba',222518);
insert into City values (39,'Batna','DZA','Batna',183377);
insert into City values (40,'Stif','DZA','Stif',179055);
insert into City values (41,'Sidi Bel Abbs','DZA','Sidi Bel Abbs',153106);
insert into City values (42,'Skikda','DZA','Skikda',128747);
insert into City values (43,'Biskra','DZA','Biskra',128281);
insert into City values (44,'Blida (el-Boulaida)','DZA','Blida',127284);
insert into City values (45,'Bjaa','DZA','Bjaa',117162);
insert into City values (46,'Mostaganem','DZA','Mostaganem',115212);
insert into City values (47,'Tbessa','DZA','Tbessa',112007);
insert into City values (48,'Tlemcen (Tilimsen)','DZA','Tlemcen',110242);
insert into City values (49,'Bchar','DZA','Bchar',107311);
insert into City values (50,'Tiaret','DZA','Tiaret',100118);
insert into City values (51,'Ech-Chleff (el-Asnam)','DZA','Chlef',96794);
insert into City values (52,'Ghardaa','DZA','Ghardaa',89415);
insert into City values (53,'Tafuna','ASM','Tutuila',5200);
insert into City values (54,'Fagatogo','ASM','Tutuila',2323);
insert into City values (55,'Andorra la Vella','AND','Andorra la Vella',21189);
insert into City values (56,'Luanda','AGO','Luanda',2022000);
insert into City values (57,'Huambo','AGO','Huambo',163100);
insert into City values (58,'Lobito','AGO','Benguela',130000);
insert into City values (59,'Benguela','AGO','Benguela',128300);
insert into City values (60,'Namibe','AGO','Namibe',118200);
insert into City values (61,'South Hill','AIA','',961);
insert into City values (62,'The Valley','AIA','',595);
insert into City values (63,'Saint Johns','ATG','St John',24000);
insert into City values (64,'Dubai','ARE','Dubai',669181);
insert into City values (65,'Abu Dhabi','ARE','Abu Dhabi',398695);
insert into City values (66,'Sharja','ARE','Sharja',320095);
insert into City values (67,'al-Ayn','ARE','Abu Dhabi',225970);
insert into City values (68,'Ajman','ARE','Ajman',114395);
insert into City values (69,'Buenos Aires','ARG','Distrito Federal',2982146);
insert into City values (70,'La Matanza','ARG','Buenos Aires',1266461);
insert into City values (71,'Crdoba','ARG','Crdoba',1157507);
insert into City values (72,'Rosario','ARG','Santa F',907718);
insert into City values (73,'Lomas de Zamora','ARG','Buenos Aires',622013);
insert into City values (74,'Quilmes','ARG','Buenos Aires',559249);
insert into City values (75,'Almirante Brown','ARG','Buenos Aires',538918);
insert into City values (76,'La Plata','ARG','Buenos Aires',521936);
insert into City values (77,'Mar del Plata','ARG','Buenos Aires',512880);
insert into City values (78,'San Miguel de Tucumn','ARG','Tucumn',470809);
insert into City values (79,'Lans','ARG','Buenos Aires',469735);
insert into City values (80,'Merlo','ARG','Buenos Aires',463846);
insert into City values (81,'General San Martn','ARG','Buenos Aires',422542);
insert into City values (82,'Salta','ARG','Salta',367550);
insert into City values (83,'Moreno','ARG','Buenos Aires',356993);
insert into City values (84,'Santa F','ARG','Santa F',353063);
insert into City values (85,'Avellaneda','ARG','Buenos Aires',353046);
insert into City values (86,'Tres de Febrero','ARG','Buenos Aires',352311);
insert into City values (87,'Morn','ARG','Buenos Aires',349246);
insert into City values (88,'Florencio Varela','ARG','Buenos Aires',315432);
insert into City values (89,'San Isidro','ARG','Buenos Aires',306341);
insert into City values (90,'Tigre','ARG','Buenos Aires',296226);
insert into City values (91,'Malvinas Argentinas','ARG','Buenos Aires',290335);
insert into City values (92,'Vicente Lpez','ARG','Buenos Aires',288341);
insert into City values (93,'Berazategui','ARG','Buenos Aires',276916);
insert into City values (94,'Corrientes','ARG','Corrientes',258103);
insert into City values (95,'San Miguel','ARG','Buenos Aires',248700);
insert into City values (96,'Baha Blanca','ARG','Buenos Aires',239810);
insert into City values (97,'Esteban Echeverra','ARG','Buenos Aires',235760);
insert into City values (98,'Resistencia','ARG','Chaco',229212);
insert into City values (99,'Jos C. Paz','ARG','Buenos Aires',221754);
insert into City values (100,'Paran','ARG','Entre Rios',207041);
insert into CountryLanguage values ('ABW','Dutch','T',5.3);
insert into CountryLanguage values ('AFG','Balochi','F',0.9);
insert into CountryLanguage values ('AGO','Ambo','F',2.4);
insert into CountryLanguage values ('AIA','English','T',0.0);
insert into CountryLanguage values ('ALB','Albaniana','T',97.9);
insert into CountryLanguage values ('AND','Catalan','T',32.3);
insert into CountryLanguage values ('ANT','Dutch','T',0.0);
insert into CountryLanguage values ('ARE','Arabic','T',42.0);
insert into CountryLanguage values ('ARG','Indian Languages','F',0.3);
insert into CountryLanguage values ('ARM','Armenian','T',93.4);
insert into CountryLanguage values ('ASM','English','T',3.1);
insert into CountryLanguage values ('ATG','Creole English','F',95.7);
insert into CountryLanguage values ('AUS','Arabic','F',1.0);
insert into CountryLanguage values ('AUT','Czech','F',0.2);
insert into CountryLanguage values ('AZE','Armenian','F',2.0);
insert into CountryLanguage values ('BDI','French','T',0.0);
insert into CountryLanguage values ('BEL','Arabic','F',1.6);
insert into CountryLanguage values ('BEN','Adja','F',11.1);
insert into CountryLanguage values ('BFA','Busansi','F',3.5);
insert into CountryLanguage values ('BGD','Bengali','T',97.7);
insert into CountryLanguage values ('BGR','Bulgariana','T',83.2);
insert into CountryLanguage values ('BHR','Arabic','T',67.7);
insert into CountryLanguage values ('BHS','Creole English','F',89.7);
insert into CountryLanguage values ('BIH','Serbo-Croatian','T',99.2);
insert into CountryLanguage values ('BLZ','English','T',50.8);
insert into CountryLanguage values ('BMU','English','T',100.0);
insert into CountryLanguage values ('BOL','Aimar','T',3.2);
insert into CountryLanguage values ('BRA','German','F',0.5);
insert into CountryLanguage values ('BRB','Bajan','F',95.1);
insert into CountryLanguage values ('BRN','Chinese','F',9.3);
insert into CountryLanguage values ('BTN','Asami','F',15.2);
insert into CountryLanguage values ('BWA','Khoekhoe','F',2.5);
insert into CountryLanguage values ('CAF','Banda','F',23.5);
insert into CountryLanguage values ('CAF','Sara','F',6.4);
insert into CountryLanguage values ('CAN','Chinese','F',2.5);
insert into CountryLanguage values ('CCK','English','T',0.0);
insert into CountryLanguage values ('CHE','French','T',19.2);
insert into CountryLanguage values ('CHE','Romansh','T',0.6);
insert into CountryLanguage values ('CHL','Aimar','F',0.5);
insert into CountryLanguage values ('CHN','Chinese','T',92.0);
insert into CountryLanguage values ('CIV','Akan','F',30.0);
insert into CountryLanguage values ('CMR','Bamileke-bamum','F',18.6);
insert into CountryLanguage values ('COD','Boa','F',2.3);
insert into CountryLanguage values ('COG','Kongo','F',51.5);
insert into CountryLanguage values ('COK','English','F',0.0);
insert into CountryLanguage values ('COL','Arawakan','F',0.1);
insert into CountryLanguage values ('COM','Comorian','T',75.0);
insert into CountryLanguage values ('CPV','Crioulo','F',100.0);
insert into CountryLanguage values ('CRI','Chibcha','F',0.3);
insert into CountryLanguage values ('CUB','Spanish','T',100.0);
insert into CountryLanguage values ('CXR','Chinese','F',0.0);
insert into CountryLanguage values ('CYM','English','T',0.0);
insert into CountryLanguage values ('CYP','Turkish','T',22.4);
insert into CountryLanguage values ('CZE','Slovak','F',3.1);
insert into CountryLanguage values ('DEU','Southern Slavic Languages','F',1.4);
insert into CountryLanguage values ('DEU','Turkish','F',2.6);
insert into CountryLanguage values ('DJI','Arabic','T',10.6);
insert into CountryLanguage values ('DMA','Creole English','F',100.0);